version: '3.1'
services:
  urlshortener_mysql:
    image: mysql:8.0.35
    container_name: docker_urlshortener_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    ports:
      - "53306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_PASSWORD']
      timeout: 5s
      retries: 12
  urlshortener_redis:
    image: redis:7.0.14
    ports:
      - "56379:6379"
    restart: always
